Platform:
    type: object
    config:
        fields:
            _repository:
                type: Repository
                resolve: { }
                description: "eZ Platform repository API"
                public: "@=hasEzAccessToOneOf('section/view', 'class/create', 'role/read')"
