services:
    BD\EzPlatformGraphQLBundle\Command\GeneratePlatformDomainTypesCommand:
        parent: BD\EzPlatformGraphQLBundle\Command\GeneratePlatformSchemaCommand
        tags:
            -  { name: console.command }

    BD\EzPlatformGraphQLBundle\Command\GeneratePlatformSchemaCommand:
        autoconfigure: true
        autowire: true
        tags:
            -  { name: console.command }
        arguments:
            $typeGenerator: '@overblog_graphql.cache_compiler'

    BD\EzPlatformGraphQLBundle\GraphQL\TypeDefinition\ContentTypeMapper: ~

    bd_ezplatform_graphql.graph.mutation.section:
        class: BD\EzPlatformGraphQLBundle\GraphQL\Mutation\SectionMutation
        arguments:
            - "@ezpublish.api.service.section"
        tags:
            - { name: "overblog_graphql.mutation", alias: "CreateSection", method: "createSection" }
            - { name: "overblog_graphql.mutation", alias: "DeleteSection", method: "deleteSection" }

    BD\EzPlatformGraphQLBundle\GraphQL\InputMapper\SearchQueryMapper: ~
