services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    BD\EzPlatformGraphQLBundle\Command\GeneratePlatformSchemaCommand:
        tags:
            -  { name: console.command }

    BD\EzPlatformGraphQLBundle\Command\GeneratePlatformDomainTypesCommand:
        tags:
            -  { name: console.command }

    BD\EzPlatformGraphQLBundle\GraphQL\Resolver\LocationResolver:
        arguments:
            - "@ezpublish.api.repository"

    BD\EzPlatformGraphQLBundle\GraphQL\TypeDefinition\ContentTypeMapper: ~


    BD\EzPlatformGraphQLBundle\GraphQL\Mutation\SectionMutation:
        arguments:
            - "@ezpublish.api.service.section"
        tags:
            - { name: "overblog_graphql.mutation", alias: "CreateSection", method: "createSection" }
            - { name: "overblog_graphql.mutation", alias: "DeleteSection", method: "deleteSection" }

    BD\EzPlatformGraphQLBundle\GraphQL\InputMapper\SearchQueryMapper: ~
